from PyQt5 import QtCore, QtGui, QtWidgets
import os
import pyqtgraph as pg

class Ui_MainWindow(QtGui.QMainWindow):

    ##--> define user interface elements
    def setupUi(self, MainWindow, parent_path):

        # Background and foreground for graphs
        pg.setConfigOption('background', (255, 255, 255))
        pg.setConfigOption('foreground', 'k')

        # Fonts
        font_headline = QtGui.QFont()
        font_headline.setPointSize(8)
        font_headline.setBold(True)

        font_graphs = QtGui.QFont()
        font_graphs.setPixelSize(10)
        font_graphs.setBold(False)

        font_graphs_2 = QtGui.QFont()
        font_graphs_2.setPixelSize(1)
        font_graphs_2.setBold(False)

        font_ee = QtGui.QFont()
        font_ee.setPointSize(7)
        font_ee.setBold(False)

        # Main Window
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(910, 751)
        MainWindow.setMinimumSize(QtCore.QSize(910, 751))
        MainWindow.setMaximumSize(QtCore.QSize(910, 751))
        MainWindow.setFont(font_ee)
        MainWindow.setWindowIcon(QtGui.QIcon(parent_path + "\icon.png"))
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setWindowTitle("BoToFit")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Block: Data file and structure
        self.label_data_file = QtWidgets.QLabel(self.centralwidget)
        self.label_data_file.setGeometry(QtCore.QRect(20, 0, 191, 16))
        self.label_data_file.setFont(font_headline)
        self.label_data_file.setObjectName("label_data_file")
        self.label_data_file.setText("Data file and structure:")
        self.groupBox_data_file = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_data_file.setGeometry(QtCore.QRect(10, 0, 551, 50))
        self.groupBox_data_file.setObjectName("groupBox_data_file")
        self.toolButton_data_file = QtWidgets.QToolButton(self.groupBox_data_file)
        self.toolButton_data_file.setGeometry(QtCore.QRect(318, 23, 26, 21))
        self.toolButton_data_file.setObjectName("toolButton_data_file")
        self.toolButton_data_file.setText("...")
        self.lineEdit_data_file = QtWidgets.QLineEdit(self.groupBox_data_file)
        self.lineEdit_data_file.setGeometry(QtCore.QRect(5, 23, 310, 21))
        self.lineEdit_data_file.setFont(font_ee)
        self.lineEdit_data_file.setObjectName("lineEdit_data_file")
        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox_data_file)
        self.comboBox_1.setGeometry(QtCore.QRect(355, 23, 61, 21))
        self.comboBox_1.setFont(font_ee)
        self.comboBox_1.setObjectName("comboBox_1")
        for i in range(0, 4): self.comboBox_1.addItem("")
        self.comboBox_1.setItemText(0, "ang(Qz)")
        self.comboBox_1.setItemText(1, "I")
        self.comboBox_1.setItemText(2, "dI")
        self.comboBox_1.setItemText(3, "ang(rad)")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_data_file)
        self.comboBox_2.setGeometry(QtCore.QRect(420, 23, 61, 21))
        self.comboBox_2.setFont(font_ee)
        self.comboBox_2.setObjectName("comboBox_2")
        for i in range(0, 4): self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "I")
        self.comboBox_2.setItemText(1, "dI")
        self.comboBox_2.setItemText(2, "ang(Qz)")
        self.comboBox_2.setItemText(3, "ang(rad)")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_data_file)
        self.comboBox_3.setGeometry(QtCore.QRect(485, 23, 61, 21))
        self.comboBox_3.setFont(font_ee)
        self.comboBox_3.setObjectName("comboBox_3")
        for i in range(0, 4): self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "dI")
        self.comboBox_3.setItemText(1, "I")
        self.comboBox_3.setItemText(2, "ang(Qz)")
        self.comboBox_3.setItemText(3, "ang(rad)")

        # Block: Start fit with
        self.label_start_fit_with = QtWidgets.QLabel(self.centralwidget)
        self.label_start_fit_with.setGeometry(QtCore.QRect(20, 50, 141, 16))
        self.label_start_fit_with.setFont(font_headline)
        self.label_start_fit_with.setObjectName("label_start_fit_with")
        self.label_start_fit_with.setText("Start fit with:")
        self.groupBox_start_fit_with = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_start_fit_with.setGeometry(QtCore.QRect(10, 50, 551, 289))
        self.groupBox_start_fit_with.setObjectName("groupBox_start_fit_with")
        self.tabWidget_data_for_fitting = QtWidgets.QTabWidget(self.groupBox_start_fit_with)
        self.tabWidget_data_for_fitting.setGeometry(QtCore.QRect(1, 18, 550, 272))
        self.tabWidget_data_for_fitting.setFont(font_ee)
        self.tabWidget_data_for_fitting.setObjectName("tabWidget_data_for_fitting")

        # - tab "Film description"
        self.Tab_film_description = QtWidgets.QWidget()
        self.Tab_film_description.setObjectName("Tab_film_description")
        self.tabWidget_data_for_fitting.addTab(self.Tab_film_description, "")
        self.tabWidget_data_for_fitting.setTabText(self.tabWidget_data_for_fitting.indexOf(self.Tab_film_description),
                                                   "Film description")
        self.pushButton_add_layer = QtWidgets.QPushButton(self.Tab_film_description)
        self.pushButton_add_layer.setGeometry(QtCore.QRect(377, 225, 80, 20))
        self.pushButton_add_layer.setObjectName("pushButton_add_layer")
        self.pushButton_add_layer.setText("Add layer")
        self.pushButton_remove_layer = QtWidgets.QPushButton(self.Tab_film_description)
        self.pushButton_remove_layer.setGeometry(QtCore.QRect(463, 225, 80, 20))
        self.pushButton_remove_layer.setObjectName("pushButton_remove_layer")
        self.pushButton_remove_layer.setText("Remove layer")
        self.tableWidget_film = QtWidgets.QTableWidget(self.Tab_film_description)
        self.tableWidget_film.setGeometry(QtCore.QRect(-2, -1, 550, 224))
        self.tableWidget_film.setFont(font_ee)
        self.tableWidget_film.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_film.setObjectName("tableWidget_film")
        self.tableWidget_film.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_film.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_film.setColumnCount(13)
        self.tableWidget_film.setRowCount(1)
        # reform the table if Pol/NoPol mode is chosen
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_film.setVerticalHeaderItem(0, item)
        for i in range(0, 13):
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget_film.setHorizontalHeaderItem(i, item)
        item = self.tableWidget_film.verticalHeaderItem(0)
        item.setText("substrate")
        item = self.tableWidget_film.horizontalHeaderItem(0)
        item.setText("name")
        item = self.tableWidget_film.horizontalHeaderItem(1)
        item.setText("thickness")
        item = self.tableWidget_film.horizontalHeaderItem(3)
        item.setText("SLD")
        item = self.tableWidget_film.horizontalHeaderItem(5)
        item.setText("iSLD")
        item = self.tableWidget_film.horizontalHeaderItem(7)
        item.setText("mSLD")
        item = self.tableWidget_film.horizontalHeaderItem(9)
        item.setText("cos(d-gamma)")
        item = self.tableWidget_film.horizontalHeaderItem(11)
        item.setText("roughness")
        for i in range(0, 13):
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            if i in (0, 1, 2): item.setFlags(QtCore.Qt.NoItemFlags)
            if i in (4, 6, 8, 10, 12):
                item.setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
                if i == 8:
                    item.setCheckState(QtCore.Qt.Unchecked)
                else:
                    item.setCheckState(QtCore.Qt.Checked)
            self.tableWidget_film.setItem(0, i, item)
        item = self.tableWidget_film.item(0, 0)
        item.setText("substrate")
        item = self.tableWidget_film.item(0, 1)
        item.setText("inf")
        item = self.tableWidget_film.item(0, 3)
        item.setText("2.07")
        item = self.tableWidget_film.item(0, 5)
        item.setText("0")
        item = self.tableWidget_film.item(0, 11)
        item.setText("10")
        self.tableWidget_film.setRowHeight(0, 21)
        self.tableWidget_film.horizontalHeader().setDefaultSectionSize(23)
        self.tableWidget_film.verticalHeader().setVisible(False)
        self.pushButton_load_entry = QtWidgets.QPushButton(self.Tab_film_description)
        self.pushButton_load_entry.setGeometry(QtCore.QRect(0, 225, 111, 20))
        self.pushButton_load_entry.setObjectName("pushButton_load_entry")
        self.pushButton_load_entry.setText("Load entry file")

        # - tab "Scan parameters"
        x_allignm = 8 # multiplier of the position's X
        y_allignm = 9  # multiplier of the position's Y
        y_size = 17 # size of the elements in Y
        x_size_linedit = 60 # linedit_size
        self.tab_scan_param = QtWidgets.QWidget()
        self.tab_scan_param.setObjectName("tab_scan_param")
        self.tabWidget_data_for_fitting.addTab(self.tab_scan_param, "")
        self.tabWidget_data_for_fitting.setTabText(self.tabWidget_data_for_fitting.indexOf(self.tab_scan_param),
                                                   "Scan parameters")
        self.label_n_of_pts_f_resol_funct = QtWidgets.QLabel(self.tab_scan_param)
        self.label_n_of_pts_f_resol_funct.setGeometry(QtCore.QRect(x_allignm, y_allignm, 311, y_size))
        self.label_n_of_pts_f_resol_funct.setFont(font_ee)
        self.label_n_of_pts_f_resol_funct.setObjectName("label_n_of_pts_f_resol_funct")
        self.label_n_of_pts_f_resol_funct.setText("Number of points for resolution function")
        self.lineEdit_n_of_pts_f_resol_funct = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_n_of_pts_f_resol_funct.setGeometry(QtCore.QRect(x_allignm * 26 - 20, y_allignm, x_size_linedit, y_size))
        self.lineEdit_n_of_pts_f_resol_funct.setFont(font_ee)
        self.lineEdit_n_of_pts_f_resol_funct.setObjectName("lineEdit_n_of_pts_f_resol_funct")
        self.label_step_f_resol_funct = QtWidgets.QLabel(self.tab_scan_param)
        self.label_step_f_resol_funct.setGeometry(QtCore.QRect(x_allignm, y_allignm*3, 291, y_size))
        self.label_step_f_resol_funct.setFont(font_ee)
        self.label_step_f_resol_funct.setObjectName("label_step_f_resol_funct")
        self.label_step_f_resol_funct.setText("Step for resolution function (mrad)")
        self.lineEdit_step_f_resol_funct = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_step_f_resol_funct.setGeometry(QtCore.QRect(x_allignm * 26 - 20, y_allignm*3, x_size_linedit, y_size))
        self.lineEdit_step_f_resol_funct.setFont(font_ee)
        self.lineEdit_step_f_resol_funct.setObjectName("lineEdit_step_f_resol_funct")
        self.label_sigma = QtWidgets.QLabel(self.tab_scan_param)
        self.label_sigma.setGeometry(QtCore.QRect(x_allignm, y_allignm*5, 291, y_size))
        self.label_sigma.setFont(font_ee)
        self.label_sigma.setObjectName("label_sigma")
        self.label_sigma.setText("\"Sigma\" of resolution function (mrad)")
        self.lineEdit_sigma = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_sigma.setGeometry(QtCore.QRect(x_allignm * 26 - 20, y_allignm*5, x_size_linedit, y_size))
        self.lineEdit_sigma.setFont(font_ee)
        self.lineEdit_sigma.setObjectName("lineEdit_sigma")
        self.label_zero_correction = QtWidgets.QLabel(self.tab_scan_param)
        self.label_zero_correction.setGeometry(QtCore.QRect(x_allignm, y_allignm*7, 281, y_size))
        self.label_zero_correction.setFont(font_ee)
        self.label_zero_correction.setObjectName("label_zero_correction")
        self.label_zero_correction.setText("Correction of the detector \"zero\"")
        self.lineEdit_zero_correction = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_zero_correction.setGeometry(QtCore.QRect(x_allignm * 26 - 20, y_allignm*7, x_size_linedit, y_size))
        self.lineEdit_zero_correction.setFont(font_ee)
        self.lineEdit_zero_correction.setObjectName("lineEdit_zero_correction")

        self.label_cross_overill = QtWidgets.QLabel(self.tab_scan_param)
        self.label_cross_overill.setGeometry(QtCore.QRect(x_allignm * 35, y_allignm*7, 311, y_size))
        self.label_cross_overill.setFont(font_ee)
        self.label_cross_overill.setObjectName("label_cross_overill")
        self.label_cross_overill.setText("Crossover angle overillumination (mrad)")
        self.lineEdit_cross_overill = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_cross_overill.setGeometry(QtCore.QRect(x_allignm * 60 - 20, y_allignm*7, x_size_linedit, y_size))
        self.lineEdit_cross_overill.setFont(font_ee)
        self.lineEdit_cross_overill.setObjectName("lineEdit_cross_overill")
        self.checkBox_cross_overill = QtWidgets.QCheckBox(self.tab_scan_param)
        self.checkBox_cross_overill.setGeometry(QtCore.QRect(x_allignm * 66 - 5, y_allignm*7, 21, y_size+1))
        self.checkBox_cross_overill.setObjectName("checkBox_cross_overill")

        self.label_wavelength = QtWidgets.QLabel(self.tab_scan_param)
        self.label_wavelength.setGeometry(QtCore.QRect(x_allignm * 35, y_allignm, 131, y_size))
        self.label_wavelength.setFont(font_ee)
        self.label_wavelength.setObjectName("label_wavelength")
        self.label_wavelength.setText("Wavelength (A)")
        self.lineEdit_wavelength = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_wavelength.setGeometry(QtCore.QRect(x_allignm * 60 - 20, y_allignm, x_size_linedit, y_size))
        self.lineEdit_wavelength.setFont(font_ee)
        self.lineEdit_wavelength.setObjectName("lineEdit_wavelength")
        self.label_scaling_factor = QtWidgets.QLabel(self.tab_scan_param)
        self.label_scaling_factor.setGeometry(QtCore.QRect(x_allignm * 35, y_allignm*3, 101, y_size))
        self.label_scaling_factor.setFont(font_ee)
        self.label_scaling_factor.setObjectName("label_scaling_factor")
        self.label_scaling_factor.setText("Scaling factor")
        self.lineEdit_scaling_factor = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_scaling_factor.setGeometry(QtCore.QRect(x_allignm * 60 - 20, y_allignm*3, x_size_linedit, y_size))
        self.lineEdit_scaling_factor.setFont(font_ee)
        self.lineEdit_scaling_factor.setPlaceholderText("")
        self.lineEdit_scaling_factor.setObjectName("lineEdit_scaling_factor")
        self.checkBox_scaling_factor = QtWidgets.QCheckBox(self.tab_scan_param)
        self.checkBox_scaling_factor.setGeometry(QtCore.QRect(x_allignm * 66 - 5, y_allignm*3, 20, y_size+1))
        self.checkBox_scaling_factor.setObjectName("checkBox_scaling_factor")
        self.label_background = QtWidgets.QLabel(self.tab_scan_param)
        self.label_background.setGeometry(QtCore.QRect(x_allignm * 35, y_allignm*5, 91, y_size))
        self.label_background.setFont(font_ee)
        self.label_background.setObjectName("label_background")
        self.label_background.setText("Background")
        self.lineEdit_background = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_background.setGeometry(QtCore.QRect(x_allignm * 60 - 20, y_allignm*5, x_size_linedit, y_size))
        self.lineEdit_background.setFont(font_ee)
        self.lineEdit_background.setObjectName("lineEdit_background")
        self.checkBox_background = QtWidgets.QCheckBox(self.tab_scan_param)
        self.checkBox_background.setGeometry(QtCore.QRect(x_allignm * 66 - 5, y_allignm*5, 21, y_size+1))
        self.checkBox_background.setObjectName("checkBox_background")

        self.label_exclude_first = QtWidgets.QLabel(self.tab_scan_param)
        self.label_exclude_first.setGeometry(QtCore.QRect(x_allignm, y_allignm*12-15, 191, 16))
        self.label_exclude_first.setObjectName("label_exclude_first")
        self.label_exclude_first.setText("Number of first points to exclude")
        self.lineEdit_exclude_first = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_exclude_first.setGeometry(QtCore.QRect(x_allignm * 26 - 20, y_allignm*12-15, x_size_linedit, y_size))
        self.lineEdit_exclude_first.setObjectName("lineEdit_exclude_first")
        self.lineEdit_exclude_first.setText("5")
        self.label_exclude_last = QtWidgets.QLabel(self.tab_scan_param)
        self.label_exclude_last.setGeometry(QtCore.QRect(x_allignm, y_allignm*14-15, 191, y_size))
        self.label_exclude_last.setObjectName("label_exclude_last")
        self.label_exclude_last.setText("Number of last points to exclude")
        self.lineEdit_exclude_last = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_exclude_last.setGeometry(QtCore.QRect(x_allignm * 26 - 20, y_allignm*14-15, x_size_linedit, y_size))
        self.lineEdit_exclude_last.setObjectName("lineEdit_exclude_last")
        self.lineEdit_exclude_last.setText("5")
        self.pushButton_redraw_refl = QtWidgets.QPushButton(self.tab_scan_param)
        self.pushButton_redraw_refl.setGeometry(QtCore.QRect(x_allignm * 32, y_allignm * 12 - 15, 121, y_size * 2))
        self.pushButton_redraw_refl.setObjectName("pushButton_redraw_refl")
        self.pushButton_redraw_refl.setText("Redraw reflectivity")

        self.label_piy = QtWidgets.QLabel(self.tab_scan_param)
        self.label_piy.setGeometry(QtCore.QRect(x_allignm, y_allignm * 16, 291, y_size))
        self.label_piy.setObjectName("label_piy")
        self.label_piy.setText("Piy incident polarization (polariser)")
        self.lineEdit_piy = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_piy.setGeometry(QtCore.QRect(x_allignm * 31 - 20, y_allignm * 16, x_size_linedit, y_size))
        self.lineEdit_piy.setObjectName("lineEdit_piy")
        self.checkBox_piy = QtWidgets.QCheckBox(self.tab_scan_param)
        self.checkBox_piy.setGeometry(QtCore.QRect(x_allignm * 42, y_allignm * 16, 21, y_size+1))
        self.checkBox_piy.setObjectName("checkBox_piy")
        self.label_pfy = QtWidgets.QLabel(self.tab_scan_param)
        self.label_pfy.setGeometry(QtCore.QRect(x_allignm, y_allignm * 18, 251, y_size))
        self.label_pfy.setObjectName("label_pfy")
        self.label_pfy.setText("Pfy outgoing polarization (analyser)")
        self.lineEdit_pfy = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_pfy.setGeometry(QtCore.QRect(x_allignm * 31 - 20, y_allignm * 18, x_size_linedit, y_size))
        self.lineEdit_pfy.setObjectName("lineEdit_pfy")
        self.checkBox_pfy = QtWidgets.QCheckBox(self.tab_scan_param)
        self.checkBox_pfy.setGeometry(QtCore.QRect(x_allignm * 42, y_allignm * 18, 21, y_size))
        self.checkBox_pfy.setObjectName("checkBox_pfy")
        self.label_cg = QtWidgets.QLabel(self.tab_scan_param)
        self.label_cg.setGeometry(QtCore.QRect(x_allignm, y_allignm * 20, 291, y_size))
        self.label_cg.setObjectName("label_cg")
        self.label_cg.setText("cg: mean value <cos(gamma)> of big domains")
        self.lineEdit_cg = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_cg.setGeometry(QtCore.QRect(x_allignm * 31 - 20, y_allignm * 20, x_size_linedit, y_size))
        self.lineEdit_cg.setObjectName("lineEdit_cg")
        self.checkBox_cg = QtWidgets.QCheckBox(self.tab_scan_param)
        self.checkBox_cg.setGeometry(QtCore.QRect(x_allignm * 42, y_allignm * 20, 21, y_size+1))
        self.checkBox_cg.setObjectName("checkBox_cg")
        self.label_sg = QtWidgets.QLabel(self.tab_scan_param)
        self.label_sg.setGeometry(QtCore.QRect(x_allignm, y_allignm * 22, 291, y_size))
        self.label_sg.setObjectName("label_sg")
        self.label_sg.setText("sg: mean value <sin(gamma)> of big domains")
        self.lineEdit_sg = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_sg.setGeometry(QtCore.QRect(x_allignm * 31 - 20, y_allignm * 22, x_size_linedit, y_size))
        self.lineEdit_sg.setObjectName("lineEdit_sg")
        self.checkBox_sg = QtWidgets.QCheckBox(self.tab_scan_param)
        self.checkBox_sg.setGeometry(QtCore.QRect(x_allignm * 42, y_allignm * 22, 21, y_size+1))
        self.checkBox_sg.setObjectName("checkBox_sg")
        self.label_sg2 = QtWidgets.QLabel(self.tab_scan_param)
        self.label_sg2.setGeometry(QtCore.QRect(x_allignm, y_allignm * 24, 291, y_size))
        self.label_sg2.setObjectName("label_sg2")
        self.label_sg2.setText("sg2: mean value <sin^2(gamma)> of big domains")
        self.lineEdit_sg2 = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_sg2.setGeometry(QtCore.QRect(x_allignm * 31 - 20, y_allignm * 24, x_size_linedit, y_size))
        self.lineEdit_sg2.setObjectName("lineEdit_sg2")
        self.checkBox_sg2 = QtWidgets.QCheckBox(self.tab_scan_param)
        self.checkBox_sg2.setGeometry(QtCore.QRect(x_allignm * 42, y_allignm * 24, 21, y_size+1))
        self.checkBox_sg2.setObjectName("checkBox_sg2")

        self.tabWidget_data_for_fitting.setCurrentIndex(0)

        # Block: Save results at
        self.label_save_at = QtWidgets.QLabel(self.centralwidget)
        self.label_save_at.setFont(font_headline)
        self.label_save_at.setGeometry(QtCore.QRect(20, 340, 151, 16))
        self.label_save_at.setObjectName("label_save_at")
        self.label_save_at.setText("Save results at:")
        self.groupBox_save_at_dir = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_save_at_dir.setGeometry(QtCore.QRect(10, 340, 421, 50))
        self.groupBox_save_at_dir.setObjectName("groupBox_save_at_dir")
        self.lineEdit_save_at_dir = QtWidgets.QLineEdit(self.groupBox_save_at_dir)
        self.lineEdit_save_at_dir.setGeometry(QtCore.QRect(5, 23, 381, 21))
        self.lineEdit_save_at_dir.setFont(font_ee)
        self.lineEdit_save_at_dir.setObjectName("lineEdit_save_at_dir")
        self.toolButton_save_at_dir = QtWidgets.QToolButton(self.groupBox_save_at_dir)
        self.toolButton_save_at_dir.setGeometry(QtCore.QRect(390, 23, 26, 21))
        self.toolButton_save_at_dir.setObjectName("toolButton_save_at_dir")
        self.toolButton_save_at_dir.setText("...")

        # Button: Start fitting
        self.pushButton_start_fitting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_fitting.setGeometry(QtCore.QRect(440, 358, 121, 32))
        self.pushButton_start_fitting.setFont(font_headline)
        self.pushButton_start_fitting.setObjectName("pushButton_start_fitting")
        self.pushButton_start_fitting.setText("Start Fitting")

        # Block: Fit results
        self.label_fit_results = QtWidgets.QLabel(self.centralwidget)
        self.label_fit_results.setFont(font_headline)
        self.label_fit_results.setGeometry(QtCore.QRect(580, 0, 101, 16))
        self.label_fit_results.setObjectName("label_fit_results")
        self.label_fit_results.setText("Fit results:")
        self.groupBox_fit_results = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_fit_results.setGeometry(QtCore.QRect(570, 0, 331, 390))
        self.groupBox_fit_results.setObjectName("groupBox_fit_results")
        self.tableWidget_fit_results = QtWidgets.QTableWidget(self.groupBox_fit_results)
        self.tableWidget_fit_results.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_fit_results.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_fit_results.setGeometry(QtCore.QRect(1, 48, 329, 322))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tableWidget_fit_results.setPalette(palette)
        self.tableWidget_fit_results.setFont(font_ee)
        self.tableWidget_fit_results.setObjectName("tableWidget_fit_results")
        self.tableWidget_fit_results.setColumnCount(6)
        self.tableWidget_fit_results.setRowCount(0)
        for i in range(0, 6):
            item = QtWidgets.QTableWidgetItem()
            if i == 1:
                item.setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
                item.setCheckState(QtCore.Qt.Unchecked)
            self.tableWidget_fit_results.setHorizontalHeaderItem(i, item)
        item = self.tableWidget_fit_results.horizontalHeaderItem(0)
        item.setText("#")
        item = self.tableWidget_fit_results.horizontalHeaderItem(1)
        item.setText("No")
        item = self.tableWidget_fit_results.horizontalHeaderItem(2)
        item.setText("Parameter")
        item = self.tableWidget_fit_results.horizontalHeaderItem(3)
        item.setText("Value")
        item = self.tableWidget_fit_results.horizontalHeaderItem(4)
        item.setText("Error")
        item = self.tableWidget_fit_results.horizontalHeaderItem(5)
        item.setText("Factor")
        self.tableWidget_fit_results.setColumnWidth(0, 15)
        self.tableWidget_fit_results.setColumnWidth(1, 20)
        self.tableWidget_fit_results.setColumnWidth(2, 100)
        self.tableWidget_fit_results.setColumnWidth(3, 60)
        self.tableWidget_fit_results.setColumnWidth(4, 60)
        self.tableWidget_fit_results.setColumnWidth(5, int(self.tableWidget_fit_results.width() - int(
            self.tableWidget_fit_results.columnWidth(0)) - int(self.tableWidget_fit_results.columnWidth(1)) - int(self.tableWidget_fit_results.columnWidth(2)) - int(
                self.tableWidget_fit_results.columnWidth(3)) - int(self.tableWidget_fit_results.columnWidth(4) - 5)))
        self.tableWidget_fit_results.verticalHeader().setVisible(False)
        self.label_iter_numb = QtWidgets.QLabel(self.groupBox_fit_results)
        self.label_iter_numb.setGeometry(QtCore.QRect(10, 18, 161, 31))
        self.label_iter_numb.setObjectName("label_iter_numb")
        self.label_iter_numb.setText("Number of iterations:")
        self.lineEdit_iter_number = QtWidgets.QLineEdit(self.groupBox_fit_results)
        self.lineEdit_iter_number.setGeometry(QtCore.QRect(104, 23, 31, 21))
        self.lineEdit_iter_number.setFont(font_ee)
        self.lineEdit_iter_number.setReadOnly(True)
        self.lineEdit_iter_number.setObjectName("lineEdit_iter_number")
        self.label_chi_sq_norm = QtWidgets.QLabel(self.groupBox_fit_results)
        self.label_chi_sq_norm.setGeometry(QtCore.QRect(205, 18, 151, 31))
        self.label_chi_sq_norm.setObjectName("label_chi_sq_norm")
        self.label_chi_sq_norm.setText("Chi_sq.norm:")
        self.lineEdit_chi_sq = QtWidgets.QLineEdit(self.groupBox_fit_results)
        self.lineEdit_chi_sq.setGeometry(QtCore.QRect(268, 23, 58, 21))
        self.lineEdit_chi_sq.setFont(font_ee)
        self.lineEdit_chi_sq.setReadOnly(True)
        self.lineEdit_chi_sq.setObjectName("lineEdit_chi_sq")
        self.pushButton_copy_to_start_fit = QtWidgets.QPushButton(self.groupBox_fit_results)
        self.pushButton_copy_to_start_fit.setGeometry(QtCore.QRect(5, 372, 322, 15))
        self.pushButton_copy_to_start_fit.setObjectName("pushButton_copy_to_start_fit")
        self.pushButton_copy_to_start_fit.setText("Use selected (#) values in 'Start Fit With' parameters")

        # Block: Reflectivity profile and Difference
        self.label_graphs_refl_and_diff = QtWidgets.QLabel(self.centralwidget)
        self.label_graphs_refl_and_diff.setFont(font_headline)
        self.label_graphs_refl_and_diff.setGeometry(QtCore.QRect(20, 393, 541, 16))
        self.label_graphs_refl_and_diff.setObjectName("label_graphs_refl_and_diff")
        self.label_graphs_refl_and_diff.setText("Reflectivity profile (I[10e] vs. Qz[Å**-1]) and Difference (Exper/Fit):")
        self.groupBox_refl_profile = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_refl_profile.setGeometry(QtCore.QRect(10, 393, 491, 316))
        self.groupBox_refl_profile.setObjectName("groupBox_refl_profile")
        self.graphicsView_refl_profile = pg.PlotWidget(self.centralwidget)
        self.graphicsView_refl_profile.setGeometry(QtCore.QRect(12, 412, 488, 205))
        self.graphicsView_refl_profile.setObjectName("graphicsView_refl_profile")
        self.graphicsView_refl_profile.getAxis("bottom").tickFont = font_graphs
        self.graphicsView_refl_profile.getAxis("bottom").setStyle(tickTextOffset=10)
        self.graphicsView_refl_profile.getAxis("left").tickFont = font_graphs
        self.graphicsView_refl_profile.getAxis("left").setStyle(tickTextOffset=10)
        self.graphicsView_refl_profile.showAxis("top")
        self.graphicsView_refl_profile.getAxis("top").tickFont = font_graphs_2
        self.graphicsView_refl_profile.getAxis("top").setStyle(tickTextOffset=-2)
        self.graphicsView_refl_profile.showAxis("right")
        self.graphicsView_refl_profile.getAxis("right").tickFont = font_graphs_2
        self.graphicsView_refl_profile.getAxis("right").setStyle(tickTextOffset=-2)
        self.graphicsView_refl_diff = pg.PlotWidget(self.centralwidget)
        self.graphicsView_refl_diff.setGeometry(QtCore.QRect(12, 607, 488, 91))
        self.graphicsView_refl_diff.setObjectName("graphicsView_refl_diff")
        self.graphicsView_refl_diff.getAxis("bottom").tickFont = font_graphs
        self.graphicsView_refl_diff.getAxis("bottom").setStyle(tickTextOffset=10)
        self.graphicsView_refl_diff.getAxis("left").tickFont = font_graphs
        self.graphicsView_refl_diff.getAxis("left").setStyle(tickTextOffset=10)
        self.graphicsView_refl_diff.showAxis("top")
        self.graphicsView_refl_diff.getAxis("top").tickFont = font_graphs_2
        self.graphicsView_refl_diff.getAxis("top").setStyle(tickTextOffset=-2)
        self.graphicsView_refl_diff.showAxis("right")
        self.graphicsView_refl_diff.getAxis("right").tickFont = font_graphs_2
        self.graphicsView_refl_diff.getAxis("right").setStyle(tickTextOffset=-2)

        # Block: SLD profile
        self.label_sld_profile = QtWidgets.QLabel(self.centralwidget)
        self.label_sld_profile.setFont(font_headline)
        self.label_sld_profile.setGeometry(QtCore.QRect(520, 393, 481, 16))
        self.label_sld_profile.setObjectName("label_sld_profile")
        self.label_sld_profile.setText("SLD profile (SLD [in Å**-2, *10e6] vs. Distance from interface [Å]:")
        self.groupBox_sld_profile = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_sld_profile.setGeometry(QtCore.QRect(510, 393, 391, 316))
        self.groupBox_sld_profile.setObjectName("groupBox_sld_profile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.graphicsView_sld_profile = pg.PlotWidget(self.centralwidget)
        self.graphicsView_sld_profile.setGeometry(QtCore.QRect(512, 412, 388, 296))
        self.graphicsView_sld_profile.setObjectName("graphicsView_sld_profile")
        self.graphicsView_sld_profile.getAxis("bottom").tickFont = font_graphs
        self.graphicsView_sld_profile.getAxis("bottom").setStyle(tickTextOffset=10)
        self.graphicsView_sld_profile.getAxis("left").tickFont = font_graphs
        self.graphicsView_sld_profile.getAxis("left").setStyle(tickTextOffset=10)
        self.graphicsView_sld_profile.showAxis("top")
        self.graphicsView_sld_profile.getAxis("top").tickFont = font_graphs_2
        self.graphicsView_sld_profile.getAxis("top").setStyle(tickTextOffset=-2)
        self.graphicsView_sld_profile.showAxis("right")
        self.graphicsView_sld_profile.getAxis("right").tickFont = font_graphs_2
        self.graphicsView_sld_profile.getAxis("right").setStyle(tickTextOffset=-2)

        # Menu
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1229, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1228, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu_MenuBar = QtWidgets.QMenu(self.menuBar)
        self.menu_MenuBar.setObjectName("menu_MenuBar")
        self.menu_MenuBar.setTitle("Mode")
        self.menuBar.addAction(self.menu_MenuBar.menuAction())
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp.setTitle("Help")
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setCheckable(False)
        self.actionVersion.setObjectName("actionVersion")
        self.actionVersion.setText("V. 1.0")
        self.menuHelp.addAction(self.actionVersion)
        MainWindow.setMenuBar(self.menuBar)
        self.menu_mono = QtWidgets.QMenu(self.menu_MenuBar)
        self.menu_mono.setObjectName("menu_mono")
        self.menu_mono.setTitle("Mono")
        self.menu_MenuBar.addAction(self.menu_mono.menuAction())
        self.menu_tof = QtWidgets.QMenu(self.menu_MenuBar)
        self.menu_tof.setObjectName("menu_tof")
        self.menu_tof.setTitle("TOF")
        self.menu_MenuBar.addAction(self.menu_tof.menuAction())
        self.action_mono_no_polarisation = QtWidgets.QAction(MainWindow)
        self.action_mono_no_polarisation.setCheckable(True)
        self.action_mono_no_polarisation.setChecked(True)
        self.action_mono_no_polarisation.setObjectName("action_mono_no_polarisation")
        self.action_mono_no_polarisation.setText("No polarisation")
        self.menu_mono.addAction(self.action_mono_no_polarisation)
        self.action_mono_2_polarisations = QtWidgets.QAction(MainWindow)
        self.action_mono_2_polarisations.setCheckable(True)
        self.action_mono_2_polarisations.setEnabled(True)
        self.action_mono_2_polarisations.setObjectName("action_mono_2_polarisations")
        self.action_mono_2_polarisations.setText("2 polarisations")
        self.menu_mono.addAction(self.action_mono_2_polarisations)
        self.action_mono_4_polarisations = QtWidgets.QAction(MainWindow)
        self.action_mono_4_polarisations.setCheckable(True)
        self.action_mono_4_polarisations.setEnabled(True)
        self.action_mono_4_polarisations.setObjectName("action_mono_4_polarisations")
        self.action_mono_4_polarisations.setText("4 polarisations")
        self.menu_mono.addAction(self.action_mono_4_polarisations)
        self.action_tof_no_polarisation = QtWidgets.QAction(MainWindow)
        self.action_tof_no_polarisation.setCheckable(True)
        self.action_tof_no_polarisation.setEnabled(True)
        self.action_tof_no_polarisation.setObjectName("action_tof_no_polarisation")
        self.action_tof_no_polarisation.setText("No polarisation")
        self.menu_tof.addAction(self.action_tof_no_polarisation)
        self.action_tof_2_polarisations = QtWidgets.QAction(MainWindow)
        self.action_tof_2_polarisations.setCheckable(True)
        self.action_tof_2_polarisations.setEnabled(True)
        self.action_tof_2_polarisations.setObjectName("action_tof_2_polarisations")
        self.action_tof_2_polarisations.setText("2 polarisations")
        self.menu_tof.addAction(self.action_tof_2_polarisations)
        self.action_tof_4_polarisations = QtWidgets.QAction(MainWindow)
        self.action_tof_4_polarisations.setCheckable(True)
        self.action_tof_4_polarisations.setEnabled(True)
        self.action_tof_4_polarisations.setObjectName("action_tof_4_polarisations")
        self.action_tof_4_polarisations.setText("4 polarisations")
        self.menu_tof.addAction(self.action_tof_4_polarisations)

        # Statusbar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Error messages
        self.label_botofit_crashed = QtWidgets.QLabel(self.groupBox_fit_results)
        self.label_botofit_crashed.setGeometry(QtCore.QRect(80, 260, 551, 20))
        self.label_botofit_crashed.setObjectName("label_botofit_crashed")
        self.label_botofit_crashed.setText("BoToFit crashed. Consider using more reasonable 'Start fit' values.")
        self.label_botofit_crashed.setVisible(0)
        self.label_need_wavelength = QtWidgets.QLabel(self.groupBox_fit_results)
        self.label_need_wavelength.setGeometry(QtCore.QRect(20, 260, 551, 20))
        self.label_need_wavelength.setObjectName("label_need_wavelength")
        self.label_need_wavelength.setText("Input wavelength before importing files in Qz. Otherwice cant convert to ang(rad) for calculations.")
        self.label_need_wavelength.setVisible(0)
        # lineEdit_pts_num and tableWidget_data_points are hidden from the user. Used to avoid reopenning data file multiple times
        self.lineEdit_pts_num = QtWidgets.QLineEdit(self.tab_scan_param)
        self.lineEdit_pts_num.setEnabled(False)
        self.lineEdit_pts_num.setGeometry(QtCore.QRect(570, 290, 0, 0))
        self.lineEdit_pts_num.setObjectName("lineEdit_pts_num")

        self.tableWidget_data_points = QtWidgets.QTableWidget(self.tab_scan_param)
        self.tableWidget_data_points.setEnabled(False)
        self.tableWidget_data_points.setGeometry(QtCore.QRect(460, 200, 0, 0))
        self.tableWidget_data_points.setObjectName("tableWidget_data_points")
        self.tableWidget_data_points.setColumnCount(3)
        self.tableWidget_data_points.setRowCount(4)
        for i in range(0, 4):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_data_points.setVerticalHeaderItem(i, item)
        for i in range(0, 3):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_data_points.setHorizontalHeaderItem(i, item)
        self.tableWidget_data_points.horizontalHeader().setVisible(False)
        self.tableWidget_data_points.verticalHeader().setVisible(False)
        item = self.tableWidget_data_points.horizontalHeaderItem(0)
        item.setText("Q")
        item = self.tableWidget_data_points.horizontalHeaderItem(1)
        item.setText("I")
        item = self.tableWidget_data_points.horizontalHeaderItem(2)
        item.setText("dI")

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    ##<--
